import type { Metadata } from "next";
import { Outfit, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Magincia Intelligence — Insight. Clarity. Advantage.",
  description:
    "Education market intelligence that gives you the insight, clarity, and advantage to make better decisions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${hankenGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-1 flex-col">{children}</div>
        <footer className="w-full border-t border-navy/10 bg-cream px-6 py-10 text-xs leading-relaxed text-navy/55">
          <div className="mx-auto max-w-3xl space-y-3">
            <p>
              <span className="font-semibold uppercase tracking-widest text-vermillion">
                Beta
              </span>{" "}
              — Magincia Intelligence is an experimental service currently in beta.
            </p>
            <p>
              <strong className="text-navy/70">Disclaimer.</strong> The briefings
              and analysis on this site are generated by artificial intelligence
              from publicly available sources. They are provided for general
              information only, on an &ldquo;as is&rdquo; and &ldquo;as
              available&rdquo; basis, and are <strong>not verified, audited, or
              checked</strong> for accuracy, completeness, or currency. Content
              may be inaccurate, incomplete, out of date, or misleading.
            </p>
            <p>
              Nothing on this site constitutes professional, legal, financial,
              immigration, investment, or other advice, and it{" "}
              <strong>must not be relied upon</strong>. You should independently
              verify any information and obtain appropriate professional advice
              before acting on anything you read here.
            </p>
            <p>
              To the maximum extent permitted by law, Magincia Intelligence, its
              operators, and contributors exclude all liability for any loss,
              damage, or cost (including indirect or consequential loss) arising
              from your use of, or reliance on, this site or its content, whether
              in contract, negligence, or otherwise. Where liability cannot
              lawfully be excluded, it is limited to the maximum extent permitted
              by law. Nothing in this disclaimer excludes, restricts, or modifies
              any consumer guarantee or right that cannot be excluded under the
              Australian Consumer Law or other applicable law.
            </p>
            <p className="pt-1 text-navy/45">
              © 2026 Magincia Intelligence. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
