import type { Metadata } from "next";
import { Outfit, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
  display: "swap",
});

const SITE_NAME = "Magincia Intelligence";
const SITE_TAGLINE =
  "Daily briefings on Australian education and international education in Australia — higher ed, VET, ELICOS, schools, and ECEC policy, funding, and regulation.";

export const metadata: Metadata = {
  metadataBase: new URL("https://magincia.ai"),
  title: {
    default:
      "Magincia Intelligence — Daily Australian Education Brief",
    template: "%s — Magincia Intelligence",
  },
  description: SITE_TAGLINE,
  applicationName: SITE_NAME,
  keywords: [
    "Australian education",
    "international education in Australia",
    "Australian higher education",
    "international students Australia",
    "Australia education policy",
    "ATEC",
    "TEQSA",
    "ASQA",
    "ELICOS",
    "Australian VET",
    "Australian universities",
    "education market intelligence",
  ],
  authors: [{ name: SITE_NAME }],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: "Magincia Intelligence — Daily Australian Education Brief",
    description: SITE_TAGLINE,
    url: "https://magincia.ai",
    locale: "en_AU",
    images: [
      {
        url: "/magincia_banner.png",
        width: 1983,
        height: 793,
        alt: "Magincia Intelligence — Australian Education Market Intelligence",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Magincia Intelligence — Daily Australian Education Brief",
    description: SITE_TAGLINE,
    images: ["/magincia_banner.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${hankenGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([
              {
                "@context": "https://schema.org",
                "@type": "Organization",
                name: SITE_NAME,
                url: "https://magincia.ai",
                logo: "https://magincia.ai/magincia_logo.png",
                description: SITE_TAGLINE,
                areaServed: "AU",
                knowsAbout: [
                  "Australian education",
                  "International education in Australia",
                  "Australian higher education policy",
                  "Australian Tertiary Education Commission (ATEC)",
                  "TEQSA",
                  "ASQA",
                  "ELICOS",
                  "Australian VET",
                ],
              },
              {
                "@context": "https://schema.org",
                "@type": "WebSite",
                name: SITE_NAME,
                url: "https://magincia.ai",
                inLanguage: "en-AU",
                publisher: { "@type": "Organization", name: SITE_NAME },
              },
            ]),
          }}
        />
        <div className="flex flex-1 flex-col">{children}</div>
        <footer className="w-full border-t border-navy/10 bg-cream px-6 py-10 text-xs leading-relaxed text-navy/55">
          <div className="mx-auto max-w-3xl space-y-3">
            <p>
              <span className="font-semibold uppercase tracking-widest text-vermillion">
                Beta
              </span>{" "}
              — Magincia Intelligence is an experimental service currently in beta.
            </p>
            <p>
              <strong className="text-navy/70">Disclaimer.</strong> The briefings
              and analysis on this site are generated by artificial intelligence
              from publicly available sources. They are provided for general
              information only, on an &ldquo;as is&rdquo; and &ldquo;as
              available&rdquo; basis, and are <strong>not verified, audited, or
              checked</strong> for accuracy, completeness, or currency. Content
              may be inaccurate, incomplete, out of date, or misleading.
            </p>
            <p>
              Nothing on this site constitutes professional, legal, financial,
              immigration, investment, or other advice, and it{" "}
              <strong>must not be relied upon</strong>. You should independently
              verify any information and obtain appropriate professional advice
              before acting on anything you read here.
            </p>
            <p>
              To the maximum extent permitted by law, Magincia Intelligence, its
              operators, and contributors exclude all liability for any loss,
              damage, or cost (including indirect or consequential loss) arising
              from your use of, or reliance on, this site or its content, whether
              in contract, negligence, or otherwise. Where liability cannot
              lawfully be excluded, it is limited to the maximum extent permitted
              by law. Nothing in this disclaimer excludes, restricts, or modifies
              any consumer guarantee or right that cannot be excluded under the
              Australian Consumer Law or other applicable law.
            </p>
            <p className="pt-1 text-navy/45">
              © 2026 Magincia Intelligence. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
